version: "3.9"
services:
  client:
    build: client/
    ports:
      - 3000:3000

  server:
    build: server/
    ports:
      - 4000:4000
    depends_on:
      - mysqlserver
    volumes:
      - sahiden-uploads:/server/src/uploads

  mysqlserver:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sahidendb_development
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqlserver

volumes:
  mysql_data:
  sahiden-uploads:
