version: "3.4"
services:
  sahiden-app:
    container_name: sahiden
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysqlserver
    volumes:
      - sahiden-uploads:/src/uploads
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ACCESSTOKEN_SECRET_KEY=${ACCESSTOKEN_SECRET_KEY}
      - REFRESHTOKEN_SECRET_KEY=${REFRESHTOKEN_SECRET_KEY}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TRANSPORTER_USER=${TRANSPORTER_USER}
      - TRANSPORTER_PASS=${TRANSPORTER_PASS}

  mysqlserver:
    container_name: Sahiden-MySQL
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sahiden123
      MYSQL_DATABASE: sahidendb_development
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    container_name: Sahiden-Adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqlserver

volumes:
  mysql_data:
  sahiden-uploads:
